import express from "express";
import path from "path";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;
const MODEL = "qwen3.6-flash-2026-04-16";
const DASHSCOPE_API = "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions";

app.use(express.json({ limit: "5mb" }));

function getApiKey(): string {
  const key = process.env.DASHSCOPE_API_KEY;
  if (!key) {
    throw new Error("DASHSCOPE_API_KEY is missing. Please configure it in your .env file.");
  }
  return key;
}

async function callQwen(systemPrompt: string, userPrompt: string): Promise<string> {
  const key = getApiKey();
  const response = await fetch(DASHSCOPE_API, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${key}`,
    },
    body: JSON.stringify({
      model: MODEL,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      response_format: { type: "json_object" },
    }),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(`Qwen API error ${response.status}: ${errText}`);
  }

  const data: any = await response.json();
  const content = data.choices?.[0]?.message?.content;
  if (!content) {
    throw new Error("No content returned from Qwen API.");
  }
  return content;
}

// REST API endpoint for Corpus Analysis
app.post("/api/analyze", async (req, res) => {
  try {
    const { text, targetLevel, title, source, category, density } = req.body;

    if (!text || !text.trim()) {
      res.status(400).json({ error: "Text content is required for analysis." });
      return;
    }

    const level = targetLevel || "IELTS";
    const docTitle = title || "Untitled Analysis Piece";
    const docSource = source || "User Provided Corpus";
    const docCategory = category || "Academic Text";
    const currentDensity = density || "standard";

    let wordCountDesc = "5 to 8 essential academic, thematic, or functional words";
    let phraseCountDesc = "4 to 6 high-quality phrasal verbs, idioms, native collocations, or formulaic chunks";
    let patternCountDesc = "3 to 4 elegant, advanced syntactic structures";

    if (currentDensity === "low") {
      wordCountDesc = "3 to 4 essential academic, thematic, or functional words";
      phraseCountDesc = "2 to 3 high-quality phrasal verbs, idioms, or native collocations";
      patternCountDesc = "1 to 2 elegant, advanced syntactic structures";
    } else if (currentDensity === "high") {
      wordCountDesc = "12 to 18 essential academic, thematic, or functional words, exhaustively and thoroughly scanning the text for high-importance items";
      phraseCountDesc = "8 to 12 high-quality phrasal verbs, idioms, native collocations, or formulaic chunks";
      patternCountDesc = "5 to 7 advanced syntactic structures";
    }

    const systemPrompt = "You are an elite academic English corpus linguist and developer. You extract precise pedagogical lexical items and grammar patterns. Always structure outputs in absolute JSON format following the requested fields. Output only valid JSON, no markdown fences.";

    const userPrompt = `Analyze the following academic/literary text as an expert academic English corpus linguist and a senior curriculum designer specializing in high-stakes exam preparation (KET, PET, FCE, CAE, IELTS, TOEFL, GRE).

Level to target for vocabulary and grammar extraction: ${level}.
Apply Target_Level Adaptation strictly:
- Extract items that are core to ${level} or slightly challenging for this tier. Avoid items that are too elementary or too obscurely advanced for this level.
- Words block: Extract ${wordCountDesc}.
- Phrase blocks: Extract ${phraseCountDesc}.
- Sentence patterns: Extract ${patternCountDesc}.

IMPORTANT constraints:
1. "contextual_sentence" must be the exact sentence as it appears in the source text.
2. "academic_example" must be a completely fresh, authentic academic or formal example sentence generated by you to showcase how a high-tier student would produce this item in writing.
3. Every word extraction must list its correct part of speech (e.g., "noun", "verb", "adjective", "adverb", etc.) in English, lowercase.

Return a JSON object with this exact structure:
{
  "meta_data": { "title": string, "source": string, "category": string, "target_level": string },
  "vocabulary_blocks": [{ "id": string, "type": "word", "item": string, "part_of_speech": string, "definition_en": string, "contextual_sentence": string, "academic_example": string }],
  "phrase_blocks": [{ "id": string, "type": "phrase_collocation_idiom", "item": string, "definition_en": string, "contextual_sentence": string, "academic_example": string }],
  "sentence_patterns": [{ "id": string, "type": "pattern", "pattern_structure": string, "functional_purpose": string, "contextual_sentence": string, "academic_example": string }]
}

Text to analyze:
"""
${text}
"""`;

    const resultText = await callQwen(systemPrompt, userPrompt);
    const runDetails = JSON.parse(resultText);

    if (!runDetails.meta_data.title) runDetails.meta_data.title = docTitle;
    if (!runDetails.meta_data.source) runDetails.meta_data.source = docSource;
    if (!runDetails.meta_data.category) runDetails.meta_data.category = docCategory;
    runDetails.meta_data.target_level = level;

    res.json(runDetails);
  } catch (error: any) {
    console.error("Analysis failed:", error);
    res.status(500).json({ error: error.message || "An error occurred during corpus analysis." });
  }
});

// REST API endpoint for Quiz generation
app.post("/api/quiz", async (req, res) => {
  try {
    const { corpusData, spacedRepPriorityItems } = req.body;

    if (!corpusData || (!corpusData.vocabulary_blocks?.length && !corpusData.phrase_blocks?.length && !corpusData.sentence_patterns?.length)) {
      res.status(400).json({ error: "Corpus analysis data is required to generate a practice quiz." });
      return;
    }

    const level = corpusData.meta_data?.target_level || "IELTS";

    let spacedRepFocusInstruction = "";
    if (Array.isArray(spacedRepPriorityItems) && spacedRepPriorityItems.length > 0) {
      spacedRepFocusInstruction = `\n\nCRITICAL: The student struggles with these items — prioritize at least 2-3 questions targeting them:\n${JSON.stringify(spacedRepPriorityItems)}`;
    }

    const systemPrompt = "You are an elite educational assessment scientist. You create high-fidelity exam questions matching British & American assessment standards. Always output valid JSON only, no markdown fences.";

    const userPrompt = `Based on the following extracted academic English vocabulary, phrasal units, and sentence structures, generate a highly professional 5-question curriculum practice quiz aligned with ${level}.${spacedRepFocusInstruction}

Input items:
- Vocabulary Words: ${JSON.stringify(corpusData.vocabulary_blocks?.map((v: any) => v.item))}
- Phrases/Collocations: ${JSON.stringify(corpusData.phrase_blocks?.map((p: any) => p.item))}
- Syntactic Sentence Patterns: ${JSON.stringify(corpusData.sentence_patterns?.map((s: any) => s.pattern_structure))}

Construct 5 questions mixing types: "multiple-choice", "fill-in-the-blank", "sentence-rewrite".

Return JSON:
{
  "title": string,
  "level": "${level}",
  "questions": [{
    "id": string,
    "type": "multiple-choice"|"fill-in-the-blank"|"sentence-rewrite",
    "question": string,
    "options": [string] (only for multiple-choice),
    "correctAnswer": string,
    "explanation": string,
    "target_item": string
  }]
}`;

    const resultText = await callQwen(systemPrompt, userPrompt);
    res.json(JSON.parse(resultText));
  } catch (error: any) {
    console.error("Quiz generation failed:", error);
    res.status(500).json({ error: error.message || "An error occurred during quiz generation." });
  }
});

// REST API endpoint for linguistic rule/nuance explanation
app.post("/api/explain-item", async (req, res) => {
  try {
    const { item, type, partOfSpeech, definition, sentence } = req.body;

    if (!item) {
      res.status(400).json({ error: "Item name/structure is required for explanation." });
      return;
    }

    const systemPrompt = "You are an elite academic English grammarian, corpus linguist, and empathetic ESL mentor. Always return valid JSON only, no markdown fences.";

    const userPrompt = `Analyze the following linguistic item and generate a clear, engaging explanation for advanced English learners (IELTS/CAE/GRE level).

Item details:
- Name/Structure: "${item}"
- Type: ${type || "unknown"}
- Part of Speech: ${partOfSpeech || "N/A"}
- Definition/Purpose: "${definition || ""}"
- Example/Context: "${sentence || ""}"

Return JSON:
{
  "nuance_explanation": string,
  "common_pitfalls": [string, string, string],
  "collocation_suggestions": [string, string, string, string],
  "tip": string
}`;

    const resultText = await callQwen(systemPrompt, userPrompt);
    res.json(JSON.parse(resultText));
  } catch (error: any) {
    console.error("Explanation generation failed:", error);
    res.status(500).json({ error: error.message || "An error occurred during explanation generation." });
  }
});

// REST API endpoint for student writing evaluation
app.post("/api/writing-feedback", async (req, res) => {
  try {
    const { paragraph, targetItems, targetLevel } = req.body;

    if (!paragraph || !paragraph.trim()) {
      res.status(400).json({ error: "Writing paragraph is required for evaluation." });
      return;
    }

    const level = targetLevel || "IELTS";

    const systemPrompt = "You are an elite academic English writing assessor and stylistic editor. Grade with professional transparency and offer highly constructive feedback. Always return valid JSON only, no markdown fences.";

    const userPrompt = `Analyze the student's academic writing paragraph under ${level} English proficiency standards (grammatical range, lexical resource, semantic coherence).

Student Paragraph:
"""
${paragraph}
"""

Target lexical items or grammar patterns the student was instructed to implement:
${JSON.stringify(targetItems || [])}

Return JSON:
{
  "score_out_of_10": integer,
  "cefr_equivalent": string,
  "target_items_analysis": [{ "item": string, "detected": boolean, "is_correct": boolean, "usage_feedback": string }],
  "corrections": [{ "original": string, "suggestion": string, "explanation": string }],
  "strengths": [string, string, string],
  "polished_version": string
}`;

    const resultText = await callQwen(systemPrompt, userPrompt);
    res.json(JSON.parse(resultText));
  } catch (error: any) {
    console.error("Writing feedback generation failed:", error);
    res.status(500).json({ error: error.message || "An error occurred during writing feedback analysis." });
  }
});

// REST API endpoint for AI Article Reconstruction
app.post("/api/article-rewrite", async (req, res) => {
  try {
    const { topic, bandScore, selectedVocabulary, selectedPhrases, selectedPatterns } = req.body;

    if (!topic || !topic.trim()) {
      res.status(400).json({ error: "An essay topic is required for reconstruction." });
      return;
    }

    const bandStr = bandScore || "8.0";

    const systemPrompt = "You are an elite chief editor at The Economist and supreme IELTS Writing assessor. You specialize in rebuilding academic articles with sophisticated argumentation. Always return valid JSON only, no markdown fences.";

    const userPrompt = `You are a Lead Columnist at The Economist and a Principal IELTS Writing Examiner.
Write a high-caliber essay on the topic: "${topic}" incorporating the user's selected lexical and grammatical features.

Target IELTS Score: Band ${bandStr}
Tone: The Economist (intellectually rigorous, analytical, witty)

Selected elements to integrate:
- Vocabulary Words: ${JSON.stringify(selectedVocabulary || [])}
- Collocations/Phrases: ${JSON.stringify(selectedPhrases || [])}
- Sentence Patterns/Structures: ${JSON.stringify(selectedPatterns || [])}

Return JSON:
{
  "headline": string,
  "introduction": { "text": string, "analysis_zh": string },
  "body_paragraphs": [{ "text": string, "para_type": string, "analysis_zh": string }],
  "conclusion": { "text": string, "analysis_zh": string },
  "items_used_checklist": [{ "item": string, "sentence_where_used": string, "usage_analysis_zh": string }],
  "stylistic_economist_analysis_zh": string
}`;

    const resultText = await callQwen(systemPrompt, userPrompt);
    res.json(JSON.parse(resultText));
  } catch (error: any) {
    console.error("Article reconstruction failed:", error);
    res.status(500).json({ error: error.message || "An error occurred during article reconstruction." });
  }
});

// REST API endpoint for dictionary lookup
app.post("/api/dictionary-lookup", async (req, res) => {
  try {
    const { word } = req.body;

    if (!word || !word.trim()) {
      res.status(400).json({ error: "A word is required for dictionary lookup." });
      return;
    }

    const systemPrompt = "You are an elite academic English lexicographer and corpus linguist. Always return valid JSON only, no markdown fences.";

    const userPrompt = `Perform a comprehensive academic dictionary lookup for the English word: "${word.trim()}".

Return JSON:
{
  "word": string,
  "ipa": string,
  "part_of_speech": string,
  "definition": string,
  "synonyms": [{ "word": string, "nuance": string }],
  "examples": [string, string, string]
}`;

    const resultText = await callQwen(systemPrompt, userPrompt);
    res.json(JSON.parse(resultText));
  } catch (error: any) {
    console.error("Dictionary lookup failed:", error);
    res.status(500).json({ error: error.message || "An error occurred during dictionary lookup." });
  }
});

// Configure Vite middleware in development or static server in production
async function configureServer() {
  if (process.env.NODE_ENV !== "production") {
    const { createServer: createViteServer } = await import("vite");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server loaded and listening on http://0.0.0.0:${PORT} [ENV: ${process.env.NODE_ENV || "development"}]`);
  });
}

configureServer();
